- samples/AfterBlazorServerSide/Pages/ControlSamples/DataList/Index.razor
- samples/BeforeWebForms/ControlSamples/DataList/Default.aspx
- samples/BeforeWebForms/ControlSamples/DataList/StyleAttributes.aspx
- src/BlazorWebFormsComponents.Test/DataList/FlowLayout/AlternatingTemplate.razor
- src/BlazorWebFormsComponents.Test/DataList/FlowLayout/ItemStyle.razor
- src/BlazorWebFormsComponents.Test/DataList/FlowLayout/SeparatorTemplate.razor
- src/BlazorWebFormsComponents.Test/DataList/TableLayout/AlternatingTemplate.razor
- src/BlazorWebFormsComponents.Test/DataList/TableLayout/GridLines.razor
- src/BlazorWebFormsComponents.Test/DataList/TableLayout/HeaderStyle.razor
- src/BlazorWebFormsComponents.Test/DataList/TableLayout/ItemStyle.razor
- src/BlazorWebFormsComponents.Test/DataList/TableLayout/SeparatorTemplate.razor
- src/BlazorWebFormsComponents.Test/DataList/TableLayout/Simple.razor
- src/BlazorWebFormsComponents.Test/DataList/TableLayout/Tabindex.razor
- src/BlazorWebFormsComponents/AlternatingItemStyle.razor
- src/BlazorWebFormsComponents/AlternatingItemStyle.razor.cs
- src/BlazorWebFormsComponents/BaseWebFormsComponent.cs
- src/BlazorWebFormsComponents/DataList.razor
- src/BlazorWebFormsComponents/DataList.razor.cs
- src/BlazorWebFormsComponents/Enums/GridLines.cs
- src/BlazorWebFormsComponents/FontUnit.cs
- src/BlazorWebFormsComponents/ItemStyle.razor
- src/BlazorWebFormsComponents/ItemStyle.razor.cs
- src/BlazorWebFormsComponents/SeparatorStyle.razor
- src/BlazorWebFormsComponents/SeparatorStyle.razor.cs
- src/BlazorWebFormsComponents/TableItemStyle.cs
- src/BlazorWebFormsComponents/UiStyle.cs
- src/BlazorWebFormsComponents/Unit.cs
- version.json
Read only support for DataList
> V0.3.0 - Completed DataList MVP

- src/BlazorWebFormsComponents.Test/Validations/CustomValidatorTests/CallServerValidateIfValidateEmpyTextSetToTrue.razor
- src/BlazorWebFormsComponents.Test/Validations/CustomValidatorTests/InvalidCustomValidator.razor
- src/BlazorWebFormsComponents.Test/Validations/CustomValidatorTests/SkipServerValidateIfValidateEmpyTextSetToFalse.razor
- src/BlazorWebFormsComponents.Test/Validations/CustomValidatorTests/ValidCustomValidator.razor
- src/BlazorWebFormsComponents.Test/Validations/RegularExpressionValidatorTests/InvalidRegularExpressionValidator.razor
- src/BlazorWebFormsComponents.Test/Validations/RegularExpressionValidatorTests/MatchedTimeout.razor
- src/BlazorWebFormsComponents.Test/Validations/RegularExpressionValidatorTests/ValidRegularExpressionValidator.razor
- src/BlazorWebFormsComponents.Test/Validations/RequiredFieldValidatorTests/InputNumberInvalidRequiredFieldValidator.razor
- src/BlazorWebFormsComponents.Test/Validations/RequiredFieldValidatorTests/InputNumberValidRequiredFieldValidator.razor
- src/BlazorWebFormsComponents.Test/Validations/RequiredFieldValidatorTests/InputTextInvalidRequiredFieldValidator.razor
- src/BlazorWebFormsComponents.Test/Validations/RequiredFieldValidatorTests/InputTextValidRequiredFieldValidator.razor
- src/BlazorWebFormsComponents.Test/Validations/RequiredFieldValidatorTests/ShowErrorMessageIfTextIsNotProvided.razor
- src/BlazorWebFormsComponents.Test/Validations/RequiredFieldValidatorTests/ShowTextIfBothTextAndErrorMessageAreAvailable.razor
- src/BlazorWebFormsComponents.Test/Validations/ValidationSummaryTests/BulletListDisplayMode.razor
- src/BlazorWebFormsComponents.Test/Validations/ValidationSummaryTests/ListDisplayMode.razor
- src/BlazorWebFormsComponents.Test/Validations/ValidationSummaryTests/NoErrors.razor
- src/BlazorWebFormsComponents.Test/Validations/ValidationSummaryTests/SingleParagraphDisplayMode.razor
- src/BlazorWebFormsComponents.Test/_Imports.razor
- src/BlazorWebFormsComponents/Validations/AspNetValidationSummary.razor
- src/BlazorWebFormsComponents/Validations/BaseValidator.razor
- src/BlazorWebFormsComponents/Validations/BaseValidator.razor.cs
- src/BlazorWebFormsComponents/Validations/RegularExpressionValidator.cs
> Added validator tests

- src/BlazorWebFormsComponents/ColorTranslator.cs
- src/BlazorWebFormsComponents/WebColor.cs
Copy of original ColorTranslator minus the Windows-specific features to make it Web specific
> Added implementation of ColorTranslator - fixes #17

- src/BlazorWebFormsComponents.Test/Validations/CompareValidator/IntegerDataType/Invalid/InvalidIntegarDataTypeCheck.razor
- src/BlazorWebFormsComponents.Test/Validations/CompareValidator/IntegerDataType/Invalid/InvalidIntegarEqual.razor
- src/BlazorWebFormsComponents.Test/Validations/CompareValidator/IntegerDataType/Invalid/InvalidIntegarGreaterThan.razor
- src/BlazorWebFormsComponents.Test/Validations/CompareValidator/IntegerDataType/Invalid/InvalidIntegarGreaterThanEqual.razor
- src/BlazorWebFormsComponents.Test/Validations/CompareValidator/IntegerDataType/Invalid/InvalidIntegarLessThan.razor
- src/BlazorWebFormsComponents.Test/Validations/CompareValidator/IntegerDataType/Invalid/InvalidIntegarLessThanEqual.razor
- src/BlazorWebFormsComponents.Test/Validations/CompareValidator/IntegerDataType/Invalid/InvalidIntegarNotEqual.razor
- src/BlazorWebFormsComponents.Test/Validations/CompareValidator/IntegerDataType/Valid/ValidIntegarDataTypeCheck.razor
- src/BlazorWebFormsComponents.Test/Validations/CompareValidator/IntegerDataType/Valid/ValidIntegarEqual.razor
- src/BlazorWebFormsComponents.Test/Validations/CompareValidator/IntegerDataType/Valid/ValidIntegarGreaterThan.razor
- src/BlazorWebFormsComponents.Test/Validations/CompareValidator/IntegerDataType/Valid/ValidIntegarGreaterThanEqual.razor
- src/BlazorWebFormsComponents.Test/Validations/CompareValidator/IntegerDataType/Valid/ValidIntegarLessThan.razor
- src/BlazorWebFormsComponents.Test/Validations/CompareValidator/IntegerDataType/Valid/ValidIntegarLessThanEqual.razor
- src/BlazorWebFormsComponents.Test/Validations/CompareValidator/IntegerDataType/Valid/ValidIntegarNotEqual.razor
- src/BlazorWebFormsComponents.Test/_Imports.razor
- src/BlazorWebFormsComponents/Enums/ValidationCompareOperator.cs
- src/BlazorWebFormsComponents/Enums/ValidationDataType.cs
- src/BlazorWebFormsComponents/Validations/CompareValidator.cs
- src/BlazorWebFormsComponents/Validations/ComparerFactory.cs
- src/BlazorWebFormsComponents/Validations/CurrencyComparer.cs
- src/BlazorWebFormsComponents/Validations/DateComparer.cs
- src/BlazorWebFormsComponents/Validations/DoubleComparer.cs
- src/BlazorWebFormsComponents/Validations/IComparer.cs
- src/BlazorWebFormsComponents/Validations/IntegerComparer.cs
- src/BlazorWebFormsComponents/Validations/StringComparer.cs
I used (copied!) the codes from webforms source code, for each validator type so we have the exact behavior.
> Add CompareValidator

- nuget.config
- src/BlazorWebFormsComponents/BlazorWebFormsComponents.csproj
- src/BlazorWebFormsComponents/DataList.razor.cs
- src/BlazorWebFormsComponents/IHasTableItemStyle.cs
- src/BlazorWebFormsComponents/LoginControls/LoginName.razor.cs
- src/BlazorWebFormsComponents/LoginControls/LoginStatus.razor.cs
- src/BlazorWebFormsComponents/Style.cs
- src/BlazorWebFormsComponents/TableItemStyle.cs
- src/BlazorWebFormsComponents/Validations/AspNetValidationSummary.razor.cs
- src/BlazorWebFormsComponents/Validations/BaseValidator.razor.cs
Introduced StyleBuilder and located a nuget.config file to help with package restore for BeforeWebForms project
> Fix classes and styles

- .gitignore
- src/BlazorWebFormsComponents.Test/DataList/FlowLayout/DataBind.razor
- src/BlazorWebFormsComponents.Test/DataList/TableLayout/DataBind.razor
- src/BlazorWebFormsComponents/DataList.razor
Hooks up databinding in DataList
* Test done
> DataList bind item and data  (#63)

- src/BlazorWebFormsComponents.Test/LoginControls/Login/Authenticate.razor
- src/BlazorWebFormsComponents.Test/LoginControls/Login/Credential.cs
- src/BlazorWebFormsComponents.Test/LoginControls/Login/LoggedIn.razor
- src/BlazorWebFormsComponents.Test/LoginControls/Login/LoggingIn.razor
- src/BlazorWebFormsComponents.Test/LoginControls/Login/LoginError.razor
- src/BlazorWebFormsComponents/LoginControls/Login.razor.cs
> Add login control unit tests

- samples/AfterBlazorServerSide/Pages/ControlSamples/Button/Index.razor
- src/BlazorWebFormsComponents.Test/Button/Click.razor
- src/BlazorWebFormsComponents.Test/Button/Command.razor
- src/BlazorWebFormsComponents/Button.razor.cs
Will not require StateHasChanged to trigger updates.
Addition of Tests for Click and Command logic.
> Fix #117 - Fix for Button

- README.md
- docs/LinkButton.md
- src/BlazorWebFormsComponents/Button.razor
- src/BlazorWebFormsComponents/Button.razor.cs
- src/BlazorWebFormsComponents/ButtonBaseComponent.cs
- src/BlazorWebFormsComponents/Interfaces/IButtonComponent.cs
- src/BlazorWebFormsComponents/LinkButton.razor
- src/BlazorWebFormsComponents/LinkButton.razor.cs
> Add LinkButton control

- src/BlazorWebFormsComponents/Button.razor.cs
- src/BlazorWebFormsComponents/ButtonBaseComponent.cs
- src/BlazorWebFormsComponents/Interfaces/IButtonComponent.cs
- src/BlazorWebFormsComponents/LinkButton.razor
@csharpfritz could you please merge this before other PRs
> Add missing OnClientClick into Link button

- README.md
- docs/Image.md
- src/BlazorWebFormsComponents/Enums/ImageAlign.cs
- src/BlazorWebFormsComponents/Image.razor
- src/BlazorWebFormsComponents/Image.razor.cs
@csharpfritz please merge this because the `ImageButton` relies on the `Image` & `IButton`
> Add Image Control

- samples/AfterBlazorServerSide/Pages/ComponentList.razor
- samples/AfterBlazorServerSide/Pages/ControlSamples/Button/Nav.razor
- samples/AfterBlazorServerSide/Pages/ControlSamples/LinkButton/Index.razor
- samples/AfterBlazorServerSide/Pages/ControlSamples/LinkButton/JavaScript.razor
- samples/AfterBlazorServerSide/Pages/ControlSamples/LinkButton/Nav.razor
- samples/AfterBlazorServerSide/Shared/NavMenu.razor
Fixes #136
Please merge this after #140
> Add LinkButton sample

- src/BlazorWebFormsComponents.Test/LinkButton/Click.razor
- src/BlazorWebFormsComponents.Test/LinkButton/Command.razor
- src/BlazorWebFormsComponents.Test/LinkButton/Format.razor
> Add LinkButton unit tests

- README.md
> Fix control docs links

- src/BlazorWebFormsComponents/BaseWebFormsComponent.cs
- src/BlazorWebFormsComponents/JsScripts.cs
Static class contains the names of the scripts we will reference throughout our components
> Fix #105 - Added JsScripts static class 

- src/BlazorWebFormsComponents.Test/GridView/DataTableSupport.razor
- src/BlazorWebFormsComponents/BaseModelBindingComponent.cs
- src/BlazorWebFormsComponents/Extensions/DataTableExtensions.cs
- src/BlazorWebFormsComponents/GridViewColumnGenerator.cs
> GridView DataSource should be of type object

- src/BlazorWebFormsComponents.Test/GridView/AutogenerateColumns.razor
> Add more unit tests for GridView generated columns

- samples/BeforeWebForms/Site.Master
Resolved issues found when resizing the browser window and while zooming the page.
> Resolve issues with menu width while sizing browser window closes #199

- samples/AfterBlazorServerSide/Pages/ControlSamples/GridView/BindAttribute.razor
- samples/BeforeWebForms/ControlSamples/GridView/Default.aspx
- src/BlazorWebFormsComponents.Test/GridView/DataBoundFields.razor
- src/BlazorWebFormsComponents/BaseColumn.cs
- src/BlazorWebFormsComponents/BaseWebFormsComponent.cs
- src/BlazorWebFormsComponents/BoundField.razor.cs
- src/BlazorWebFormsComponents/DataBinder.cs
- src/BlazorWebFormsComponents/GridViewRow.razor
- src/BlazorWebFormsComponents/HyperLinkField.razor
- src/BlazorWebFormsComponents/HyperLinkField.razor.cs
- src/BlazorWebFormsComponents/Interfaces/IColumn.cs
- src/BlazorWebFormsComponents/TemplateField.razor.cs
This change is split into 2 commits to make it easier to review.
> GridView improvements: Change rendering ownership; add HyperLinkField

- CONTRIBUTING.md
A first cut at a resolution to this issue #230
> Add information about suggested tools for contributing fix #230

- src/BlazorWebFormsComponents.Test/ImageButton/Enabled.razor
- src/BlazorWebFormsComponents.Test/ImageButton/ImageAlign.razor
- src/BlazorWebFormsComponents.Test/ImageButton/Style.razor
- src/BlazorWebFormsComponents.Test/ImageButton/ToolTip.razor
- src/BlazorWebFormsComponents.Test/ImageButton/Visible.razor
- src/BlazorWebFormsComponents/ImageButton.razor
- src/BlazorWebFormsComponents/ImageButton.razor.cs
Fixes almost the features in #229
> Add missing ImageButton attributes

- src/BlazorWebFormsComponents.Test/Image/GenerateEmptyAlternateText.razor
- src/BlazorWebFormsComponents.Test/Image/ImageAlign.razor
- src/BlazorWebFormsComponents.Test/Image/ToolTip.razor
- src/BlazorWebFormsComponents.Test/Image/Visible.razor
- src/BlazorWebFormsComponents/Image.razor
- src/BlazorWebFormsComponents/Image.razor.cs
> Add missing Image attributes

- src/BlazorWebFormsComponents.Test/GridView/AutogenerateColumns.razor
- src/BlazorWebFormsComponents.Test/GridView/DataTableSupport.razor
- src/BlazorWebFormsComponents/GridViewColumnGenerator.cs
Fixes #203, and make the `GridView` bind the properties types that had been supported in WebForms
> Use BindableTypes()

- samples/AfterBlazorServerSide/Pages/ComponentList.razor
- samples/AfterBlazorServerSide/Pages/ControlSamples/HyperLink/Index.razor
- samples/AfterBlazorServerSide/Shared/NavMenu.razor
> Add HyperLink sample

- docs/DataControls/FormView.md
- src/BlazorWebFormsComponents.Test/FormView/Delete.razor
- src/BlazorWebFormsComponents/FormView.razor.cs
- src/BlazorWebFormsComponents/FormViewDeleteEventArgs.cs
- src/BlazorWebFormsComponents/FormViewDeletedEventArgs.cs
- src/BlazorWebFormsComponents/FormViewInsertEventArgs.cs
- version.json
* Completed Insert template with insert events
* Completed Delete mode
* Added new supported features doc for FormView
> Feature form view inserttemplate (#258)
